from typing import Optional, Any

class SPMCQueue:
    CNT: int
    
    def __init__(self, size: int = 512) -> None: ...
    def get_reader(self) -> SPMCReader: ...
    def write(self, data: Any) -> None: ...

class SPMCReader:
    def __init__(self, queue: SPMCQueue, start_idx: int) -> None: ...
    def read(self) -> Optional[Any]: ...
    def read_last(self) -> Optional[Any]: ...
