from typing import Optional, TypeVar, Generic

T = TypeVar('T')

class SPMCQueue(Generic[T]):
    CNT: int
    
    def __init__(self, size: int = 512) -> None: ...
    def get_reader(self) -> SPMCReader[T]: ...
    def write(self, data: T) -> None: ...

class SPMCReader(Generic[T]):
    def __init__(self, queue: SPMCQueue[T], start_idx: int) -> None: ...
    def read(self) -> Optional[T]: ...
    def read_last(self) -> Optional[T]: ...
